#ifndef APP_TUSB_CONFIG_H
#define APP_TUSB_CONFIG_H
#define CFG_TUSB_MCU OPT_MCU_STM32F4
#define CFG_TUSB_OS OPT_OS_FREERTOS
#define CFG_TUSB_DEBUG 0
#define CFG_TUSB_RHPORT0_MODE (OPT_MODE_DEVICE | OPT_MODE_FULL_SPEED)
#define CFG_TUD_ENDPOINT0_SIZE 64
#define CFG_TUD_TASK_QUEUE_SZ 16
#define CFG_TUD_ECM_RNDIS 1
#define CFG_TUD_NCM 0
#define CFG_TUD_NET_MTU 1514
#define CFG_TUD_NET_ENDPOINT_SIZE 64
#define CFG_TUSB_MEM_ALIGN __attribute__((aligned(4)))
#endif
