option(STM32_USB_RNDIS "Use native USB RNDIS UDP instead of USART1" OFF)
set(STM32_USB_HSE_HZ 8000000 CACHE STRING "Board external crystal frequency in Hz")
set(STM32_USB_MCU_IP "192.168.8.1" CACHE STRING "USB MCU IPv4 (/24)")
set(STM32_USB_HOST_IP "192.168.8.2" CACHE STRING "Fixed DHCP address offered to the USB host")
set(STM32_ROS_AGENT_IP "${STM32_USB_HOST_IP}" CACHE STRING "micro-ROS Agent IPv4")
set(STM32_ROS_AGENT_PORT 8888 CACHE STRING "micro-ROS Agent UDP port")
set(STM32_ROS_UART_BAUD 115200 CACHE STRING "USART1 baud rate")
include("${CMAKE_CURRENT_LIST_DIR}/menuconfig.cmake")
if(NOT ROS_DOMAIN_ID MATCHES "^[0-9]+$" OR ROS_DOMAIN_ID GREATER 232)
    message(FATAL_ERROR "ROS_DOMAIN_ID must be 0..232")
endif()
target_compile_definitions(${CMAKE_PROJECT_NAME} PRIVATE
    APP_ROS_DOMAIN_ID=${ROS_DOMAIN_ID} APP_ROS_UART_BAUD=${STM32_ROS_UART_BAUD})
if(NOT STM32_USB_RNDIS)
    return()
endif()
if(NOT STM32_USB_HSE_HZ MATCHES "^[0-9]+$" OR STM32_USB_HSE_HZ LESS 4000000 OR
   STM32_USB_HSE_HZ GREATER 26000000)
    message(FATAL_ERROR "STM32_USB_HSE_HZ must be 4..26 MHz in whole MHz units")
endif()
math(EXPR _hse_remainder "${STM32_USB_HSE_HZ} % 1000000")
if(_hse_remainder)
    message(FATAL_ERROR "STM32_USB_HSE_HZ must be a whole MHz frequency")
endif()
foreach(_key STM32_USB_MCU_IP STM32_USB_HOST_IP STM32_ROS_AGENT_IP)
    if(NOT "${${_key}}" MATCHES "^[0-9]+\\.[0-9]+\\.[0-9]+\\.[0-9]+$")
        message(FATAL_ERROR "${_key} must be numeric IPv4")
    endif()
    string(REPLACE "." ";" _octets "${${_key}}")
    foreach(_octet IN LISTS _octets)
        if(_octet GREATER 255 OR "${_octet}" MATCHES "^0[0-9]")
            message(FATAL_ERROR "Invalid IPv4 ${_key}")
        endif()
    endforeach()
    if("${${_key}}" STREQUAL "0.0.0.0" OR "${${_key}}" STREQUAL "255.255.255.255")
        message(FATAL_ERROR "${_key} must be an individual host address")
    endif()
endforeach()
string(REGEX REPLACE "\\.[0-9]+$" "" _mcu_subnet "${STM32_USB_MCU_IP}")
string(REGEX REPLACE "\\.[0-9]+$" "" _host_subnet "${STM32_USB_HOST_IP}")
if(NOT _mcu_subnet STREQUAL _host_subnet OR STM32_USB_MCU_IP STREQUAL STM32_USB_HOST_IP OR
   STM32_USB_MCU_IP MATCHES "\\.(0|255)$" OR STM32_USB_HOST_IP MATCHES "\\.(0|255)$")
    message(FATAL_ERROR "USB MCU and host must use distinct unicast addresses in the same /24")
endif()
if(NOT STM32_ROS_AGENT_PORT MATCHES "^[0-9]+$" OR STM32_ROS_AGENT_PORT LESS 1 OR STM32_ROS_AGENT_PORT GREATER 65535)
    message(FATAL_ERROR "STM32_ROS_AGENT_PORT must be 1..65535")
endif()
set(_tiny "${CMAKE_SOURCE_DIR}/Middlewares/Third_Party/TinyUSB")
set(_lwip "${CMAKE_SOURCE_DIR}/Middlewares/Third_Party/LwIP/src")
set(_net "${CMAKE_SOURCE_DIR}/Src/net")
target_include_directories(${CMAKE_PROJECT_NAME} PRIVATE ${_net} ${_lwip}/include
    ${_tiny}/src ${_tiny}/lib/networking)
target_compile_definitions(${CMAKE_PROJECT_NAME} PRIVATE APP_ROS_USB_RNDIS=1
    APP_USB_MCU_IP="${STM32_USB_MCU_IP}" APP_USB_HOST_IP="${STM32_USB_HOST_IP}"
    APP_ROS_AGENT_IP="${STM32_ROS_AGENT_IP}" APP_ROS_AGENT_PORT=${STM32_ROS_AGENT_PORT})
# HAL_RCC_GetSysClockFreq and the application must agree about HSE frequency.
target_compile_definitions(stm32cubemx INTERFACE HSE_VALUE=${STM32_USB_HSE_HZ}U)
target_sources(${CMAKE_PROJECT_NAME} PRIVATE
    ${CMAKE_SOURCE_DIR}/Src/usb_network.c ${CMAKE_SOURCE_DIR}/Src/usb_descriptors.c
    ${_net}/dhcp_protocol.c
    ${_tiny}/src/tusb.c ${_tiny}/src/common/tusb_fifo.c
    ${_tiny}/src/device/usbd.c ${_tiny}/src/class/net/ecm_rndis_device.c
    ${_tiny}/src/portable/synopsys/dwc2/dcd_dwc2.c ${_tiny}/src/portable/synopsys/dwc2/dwc2_common.c
    ${_tiny}/lib/networking/rndis_reports.c)
foreach(_source init def inet_chksum ip mem memp netif pbuf stats sys timeouts udp)
    target_sources(${CMAKE_PROJECT_NAME} PRIVATE ${_lwip}/core/${_source}.c)
endforeach()
foreach(_source etharp icmp ip4 ip4_addr)
    target_sources(${CMAKE_PROJECT_NAME} PRIVATE ${_lwip}/core/ipv4/${_source}.c)
endforeach()
target_sources(${CMAKE_PROJECT_NAME} PRIVATE ${_lwip}/netif/ethernet.c)
